# Generated by Django 4.2 on 2023-04-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_delete_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD'), ('gbp', 'GBP'), ('eur', 'EUR')], max_length=3),
        ),
    ]
